import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { cn } from '~/src/utils/css';
import { NextAuthProvider } from '~/components/layout/NextAuthProvider';
import { SWRProvider } from '~/components/layout/SWRProvider';

const geist = Geist({
  variable: '--font-geist-sans',
  display: 'swap',
  weight: ['400', '900'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(geist.variable, 'antialiased')}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <SWRProvider>
            <NextAuthProvider>{children}</NextAuthProvider>
          </SWRProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
