import type { Metadata } from 'next';
import { SidebarInset, SidebarProvider } from '~/components/ui/sidebar';
import { AppSidebar } from './app-sidebar';
import { Header } from './app-header';
import { Sheet } from '~/components/ui/sheet';
import { ToastProvider } from '~/components/layout/ToastProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <Sheet>
        <AppSidebar />

        <SidebarInset className="bg-background">
          <Header />
          <div className="px-6 md:mt-10 mt-6 pb-10">{children}</div>
        </SidebarInset>
      </Sheet>

      <ToastProvider />
    </SidebarProvider>
  );
}
